[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = "1.1.2"
serde ="1.0.144"
serde_json = "1.0.85"
chrono ="0.4.22"



